import { TeamMember } from "./types";

export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Senior Frontend Engineer",
    bio: "Building interfaces that feel like magic. 8 years in React, now deep into design systems and accessibility.",
    avatarColor: "#6366f1",
    skills: [
      { name: "React", proficiency: "expert" },
      { name: "TypeScript", proficiency: "expert" },
      { name: "Accessibility", proficiency: "advanced" },
      { name: "Design Systems", proficiency: "advanced" },
      { name: "Next.js", proficiency: "advanced" },
      { name: "CSS Architecture", proficiency: "intermediate" },
    ],
    projects: [
      { name: "Design System v3", role: "Tech Lead", status: "active" },
      { name: "Checkout Redesign", role: "Frontend Dev", status: "completed" },
      { name: "Mobile App", role: "Advisor", status: "paused" },
    ],
    availability: {
      status: "available",
      hours: "9am-5pm",
      timezone: "EST",
    },
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "2",
    name: "Marcus Williams",
    role: "Product Designer",
    bio: "Design is how it works, not how it looks. Focused on systematic design and bridging the gap between design and engineering.",
    avatarColor: "#ec4899",
    skills: [
      { name: "Figma", proficiency: "expert" },
      { name: "Design Tokens", proficiency: "advanced" },
      { name: "Prototyping", proficiency: "advanced" },
      { name: "User Research", proficiency: "intermediate" },
      { name: "CSS", proficiency: "intermediate" },
      { name: "React", proficiency: "beginner" },
    ],
    projects: [
      { name: "Design System v3", role: "Lead Designer", status: "active" },
      { name: "Brand Refresh", role: "Designer", status: "active" },
    ],
    availability: {
      status: "focused",
      hours: "10am-6pm",
      timezone: "EST",
    },
    createdAt: "2026-04-11T10:30:00Z",
  },
  {
    id: "3",
    name: "Priya Patel",
    role: "Full Stack Developer",
    bio: "API whisperer. Building scalable backends and connecting them to beautiful frontends.",
    avatarColor: "#10b981",
    skills: [
      { name: "Node.js", proficiency: "expert" },
      { name: "PostgreSQL", proficiency: "advanced" },
      { name: "React", proficiency: "advanced" },
      { name: "GraphQL", proficiency: "advanced" },
      { name: "Docker", proficiency: "intermediate" },
      { name: "AWS", proficiency: "intermediate" },
    ],
    projects: [
      { name: "API Platform", role: "Tech Lead", status: "active" },
      { name: "Data Pipeline", role: "Backend Dev", status: "active" },
      { name: "Checkout Redesign", role: "Backend Dev", status: "completed" },
    ],
    availability: {
      status: "busy",
      hours: "8am-4pm",
      timezone: "PST",
    },
    createdAt: "2026-04-12T08:00:00Z",
  },
  {
    id: "4",
    name: "James O'Brien",
    role: "Junior Developer",
    bio: "6 months in. Learning fast, breaking things faster. Excited about everything.",
    avatarColor: "#f59e0b",
    skills: [
      { name: "JavaScript", proficiency: "intermediate" },
      { name: "React", proficiency: "beginner" },
      { name: "HTML/CSS", proficiency: "intermediate" },
      { name: "Git", proficiency: "beginner" },
    ],
    projects: [
      { name: "Design System v3", role: "Developer", status: "active" },
    ],
    availability: {
      status: "available",
      hours: "9am-5pm",
      timezone: "EST",
    },
    createdAt: "2026-04-14T09:00:00Z",
  },
  {
    id: "5",
    name: "Aisha Nakamura",
    role: "Engineering Manager",
    bio: "Former IC turned manager. Still codes on weekends. Obsessed with developer experience and team health.",
    avatarColor: "#8b5cf6",
    skills: [
      { name: "People Management", proficiency: "expert" },
      { name: "Architecture", proficiency: "advanced" },
      { name: "Python", proficiency: "advanced" },
      { name: "System Design", proficiency: "advanced" },
      { name: "Agile", proficiency: "intermediate" },
    ],
    projects: [
      { name: "Team Scaling", role: "Lead", status: "active" },
      { name: "API Platform", role: "Sponsor", status: "active" },
      { name: "Hiring Pipeline", role: "Owner", status: "paused" },
    ],
    availability: {
      status: "away",
      hours: "9am-5pm",
      timezone: "CST",
    },
    createdAt: "2026-04-09T11:00:00Z",
  },
  {
    id: "6",
    name: "Tom Lindqvist",
    role: "DevOps Engineer",
    bio: "If it's not automated, it's not done. CI/CD pipelines, infrastructure as code, and making deployments boring.",
    avatarColor: "#06b6d4",
    skills: [
      { name: "Kubernetes", proficiency: "expert" },
      { name: "Terraform", proficiency: "expert" },
      { name: "AWS", proficiency: "advanced" },
      { name: "GitHub Actions", proficiency: "advanced" },
      { name: "Python", proficiency: "intermediate" },
      { name: "Monitoring", proficiency: "advanced" },
    ],
    projects: [
      { name: "Platform Migration", role: "Lead", status: "active" },
      { name: "API Platform", role: "DevOps", status: "active" },
    ],
    availability: {
      status: "available",
      hours: "7am-3pm",
      timezone: "EST",
    },
    createdAt: "2026-04-13T07:00:00Z",
  },
];

export const suggestedSkills = [
  "React", "TypeScript", "JavaScript", "Next.js", "Node.js",
  "Python", "Go", "Rust", "SQL", "PostgreSQL",
  "GraphQL", "REST APIs", "Docker", "Kubernetes", "AWS",
  "Azure", "GCP", "Terraform", "CI/CD", "Git",
  "Figma", "Design Systems", "CSS", "Tailwind", "Accessibility",
  "Testing", "TDD", "Agile", "System Design", "Architecture",
  "Machine Learning", "Data Engineering", "Mobile", "Swift", "Kotlin",
  "User Research", "Prototyping", "Leadership", "Mentoring",
];
